/** Realistic customer reviews for seeding — 20+ reviews */
export const SEED_REVIEWS = [
  { name: "Rahul S.", city: "Delhi", rating: 5, review: "Packaging was completely discreet. Delivery was fast and the product quality is excellent.", productSlug: "silicone-wellness-massager" },
  { name: "Amit K.", city: "Mumbai", rating: 5, review: "Excellent quality and COD service. No issues at all — highly recommend TrustSilcon.", productSlug: "mens-premium-wellness-device" },
  { name: "Arjun M.", city: "Bangalore", rating: 5, review: "Product quality exceeded expectations. Discreet box with no labels — exactly as promised.", productSlug: "couple-wellness-set" },
  { name: "Vikas P.", city: "Pune", rating: 5, review: "Trusted website and secure delivery. Will order again for sure.", productSlug: "starter-wellness-kit" },
  { name: "Priya R.", city: "Hyderabad", rating: 5, review: "Very happy with my purchase. Fast shipping and premium quality silicone.", productSlug: "silicone-wellness-massager" },
  { name: "Suresh N.", city: "Chennai", rating: 5, review: "COD worked perfectly. Package arrived in plain brown box — totally private.", productSlug: "luxury-gift-combo-box" },
  { name: "Deepak T.", city: "Jaipur", rating: 4, review: "Good product, fast delivery. WhatsApp support helped me choose the right item.", productSlug: "mens-premium-wellness-device" },
  { name: "Karan J.", city: "Ahmedabad", rating: 5, review: "Best wellness store in India. Discreet packaging and genuine products.", productSlug: "premium-silicone-wellness-ring" },
  { name: "Rohan B.", city: "Kolkata", rating: 5, review: "Ordered twice now. Both times delivery was quick and packaging was 100% discreet.", productSlug: "rechargeable-personal-care-device" },
  { name: "Neha G.", city: "Lucknow", rating: 5, review: "Loved the quality. Body-safe material and easy to clean. Great experience overall.", productSlug: "silicone-wellness-massager" },
  { name: "Manish D.", city: "Chandigarh", rating: 5, review: "Cash on delivery made it easy to order. Product is premium and worth every rupee.", productSlug: "starter-wellness-kit" },
  { name: "Anil V.", city: "Indore", rating: 4, review: "Solid quality product. Delivery took 4 days to my pincode — acceptable.", productSlug: "silicone-care-lube" },
  { name: "Sanjay H.", city: "Patna", rating: 5, review: "Completely satisfied. No product name on package — wife had no idea what it was.", productSlug: "couple-wellness-set" },
  { name: "Varun L.", city: "Gurgaon", rating: 5, review: "Top notch service. WhatsApp team guided me through COD order smoothly.", productSlug: "luxury-gift-combo-box" },
  { name: "Ravi C.", city: "Noida", rating: 5, review: "Trusted quality. Medical-grade silicone feels premium. Fast pan-India delivery.", productSlug: "mens-premium-wellness-device" },
  { name: "Pooja M.", city: "Surat", rating: 5, review: "Discreet delivery as advertised. Product quality is genuinely premium.", productSlug: "rechargeable-personal-care-device" },
  { name: "Harsh S.", city: "Bhopal", rating: 4, review: "Good experience. Easy checkout and COD option is very convenient.", productSlug: "premium-silicone-wellness-ring" },
  { name: "Nitin A.", city: "Kochi", rating: 5, review: "Excellent website. Secure checkout, fast shipping, and great product.", productSlug: "silicone-wellness-massager" },
  { name: "Aditya W.", city: "Nagpur", rating: 5, review: "Packaging was plain and unmarked. Product exceeded my expectations.", productSlug: "starter-wellness-kit" },
  { name: "Kunal R.", city: "Dehradun", rating: 5, review: "Repeat customer here. TrustSilcon never disappoints with quality or privacy.", productSlug: "couple-wellness-set" },
  { name: "Meera K.", city: "Visakhapatnam", rating: 5, review: "Fast delivery to my city. COD available and product is body-safe quality.", productSlug: "silicone-care-lube" },
  { name: "Ashish P.", city: "Thane", rating: 5, review: "Best purchase I've made online. Discreet, fast, and premium wellness product.", productSlug: "luxury-gift-combo-box" },
];
